if(location.hostname=="www.google.com"&&location.hash.substr(0,5)=="#:--:"&&!window.SGHistory){window.SGHistory=!0;var parts=location.hash.substr(5).split(":--:"),id=parts[0],titles=JSON.parse(unescape(parts[1])),urls=JSON.parse(unescape(parts[2])),index=location.search.substr(7)*1,decodetext=function(k){for(var v="",w=0;w<k.length;w++)v+=String.fromCharCode(k.charCodeAt(w)-10);return v};chrome.extension.sendRequest({loadhistory:index,id:id},function(k){k?location.replace(decodetext(urls[index])):
index<urls.length-1?(document.title=decodetext(titles[index]),index==0&&(location.hash+=":--:0"),location.search="?index="+(index+1),index>0&&(location.hash+=":--:0")):location.href=decodetext(urls[urls.length-1])})}chrome.extension.onRequest.addListener(function(k,v,w){k.ping&&w()});
var SmoothGestures=function(){var k=this,v=k.callback=null;chrome.extension&&chrome.extension.getURL("").substr(19,32);var w=(""+Math.random()).substr(2),H,z=!1,r=null,l=null,u=null,o=null,j={},b={},x=!1,g={},p={},s=!0,y=!1,t="0000",C=!1,A=null;k.connect=function(){var a={name:JSON.stringify({name:"smoothgestures.tab",frame:!parent,id:w,url:location.href})};if(r=window.SGextId?chrome.extension.connect(window.SGextId,a):chrome.extension.connect(a))r.onMessage.addListener(I),r.onDisconnect.addListener(k.disable)};
var I=function(a){a=JSON.parse(a);a.enable&&(z||(z=!0,window.addEventListener("mousedown",J,!0),window.addEventListener("mouseup",K,!0),window.addEventListener("click",L,!0),window.addEventListener("contextmenu",M,!0),window.addEventListener("selectstart",N,!0),window.addEventListener("resize",F,!0),window.addEventListener("keydown",O,!0)));a.disable&&k.disable();if(a.extVersion&&!v)v=a.extVersion;if(a.settings)j=a.settings;if(a.validGestures)o=a.validGestures;a.windowBlurred&&(g={},p={},s=!0,q());
a.chain&&(G(a.chain.startPoint,a.chain.startPoint?document.elementFromPoint(a.chain.startPoint.x,a.chain.startPoint.y):null,a.chain.line,a.chain.rocker,a.chain.wheel,1E4),s=!0,a.chain.buttonDown&&(a.chain.buttonDown[0]&&(p[0]=!0),a.chain.buttonDown[1]&&(p[1]=!0),a.chain.buttonDown[2]&&(p[2]=!0),g[0]==void 0&&(g[0]=a.chain.buttonDown[0]),g[1]==void 0&&(g[1]=a.chain.buttonDown[1]),g[2]==void 0&&(g[2]=a.chain.buttonDown[2])));if(a.syncButton)g[a.syncButton.id]=a.syncButton.down;a.displayAlert&&alert(a.displayAlert);
a.eval&&(new Function("port",a.eval)).apply(window,[r]);if("sgplugin"in a)H=a.sgplugin},J=function(a){p[a.button]=!1;s=a.button!=2;if(a.target&&a.target.nodeName=="HTML"&&(document.height>window.innerHeight&&a.clientX>window.innerWidth-17||document.width>window.innerWidth&&a.clientY>window.innerHeight-17))q();else{x&&r.postMessage(JSON.stringify({syncButton:{id:a.button,down:!0}}));g[a.button]=!0;if(y)if(a.button==2){q();return}else y=!1;B(a);if(b.rocker&&(g[0]?1:0)+(g[1]?1:0)+(g[2]?1:0)==2){var n,
f;g[0]&&(a.button==0?f="L":n="L");g[1]&&(a.button==1?f="M":n="M");g[2]&&(a.button==2?f="R":n="R");if(k.callback||o.r[n]&&o.r[n][f]){x={timeout:setTimeout(function(){x=!1},500)};D("r"+n+f);window.getSelection().removeAllRanges();s=!0;p[0]=!0;p[1]=!0;p[2]=!0;a.preventDefault();a.stopPropagation();return}}if(!j.contextOnLink||!(a.button==2&&P(a.target)))if(!(j.holdButton==0&&a.button==0&&a.target.nodeName=="SELECT")&&!(j.holdButton==0&&(t[0]!="0"||t[1]!="0"||t[2]!="0"||C)))j.holdButton==0&&a.button==
0&&a.target.nodeName=="IMG"&&a.preventDefault(),a.button==1&&(o.r.M||window.SG.callback)&&navigator.platform.indexOf("Win")!=-1&&a.preventDefault(),G({x:a.clientX,y:a.clientY},a.target,a.button==j.holdButton,(g[0]?1:0)+(g[1]?1:0)+(g[2]?1:0)==1&&(k.callback||o.r&&(g[0]&&o.r.L||g[1]&&o.r.M||g[2]&&o.r.R)),a.button==j.holdButton&&(k.callback||o.w))}},K=function(a){a.button==j.holdButton&&(b.line&&B(a,!0),b.line&&b.line.code!=""&&(D(b.line.code),a.preventDefault(),a.button==0&&window.getSelection().removeAllRanges(),
a.button==2&&(s=!0),p[a.button]=!0));b.line=null;b.wheel=null;a.button!=2&&(s=!0);a.button==2&&!y&&!s&&!g[0]&&!g[1]&&navigator.platform.indexOf("Win")==-1&&(y=!0,setTimeout(function(){y=!1},600),H?r.postMessage(JSON.stringify({sgplugin:{rightclick:!0}})):j.blockDoubleclickAlert||r.postMessage(JSON.stringify({alertDoubleclick:{centerX:window.screenLeft+window.outerWidth/2,centerY:window.screenTop+window.outerHeight/2}})));p[a.button]&&a.preventDefault();g[a.button]=!1;x&&r.postMessage(JSON.stringify({syncButton:{id:a.button,
down:!1}}));if(!g[0]&&!g[2])b.rocker=null},L=function(a){p[a.button]&&(a.preventDefault(),a.stopPropagation());p[a.button]=!1},M=function(a){(s||g[2]&&(b.line||b.rocker||b.wheel))&&!y?(a.preventDefault(),a.stopPropagation(),s=!1):(q(),g={})},N=function(){j.holdButton==0&&t[0]=="0"&&t[1]=="0"&&t[2]=="0"&&!C&&window.getSelection().removeAllRanges()},F=function(){l.width=window.innerWidth;l.height=window.innerHeight},O=function(a){if(a.keyCode==27){q();C=!0;var b=function(){C=!1;window.removeEventListener("keyup",
b,!0)};window.addEventListener("keyup",b,!0)}var f=(a.ctrlKey?"1":"0")+(a.altKey?"1":"0")+(a.shiftKey?"1":"0")+(a.metaKey?"1":"0");if(a.keyCode==16||a.keyCode==17||a.keyCode==18||a.keyCode==0||a.keyCode==92||a.keyCode==93){var m=a.keyCode==16?2:a.keyCode==17?0:a.keyCode==18?1:a.keyCode==0?null:a.keyCode==92?null:a.keyCode==93?null:null;m!=null&&(f=f.substr(0,m)+"1"+f.substr(m+1),b=function(){t=t.substr(0,m)+"0"+t.substr(m+1);window.removeEventListener("keyup",b,!0)},window.addEventListener("keyup",
b,!0));t=f}else if(k.callback||(f!="0000"||A==null||A.nodeName!="INPUT"&&A.nodeName!="TEXTAREA")&&o.k&&o.k[f]&&o.k[f].indexOf(a.keyIdentifier+":"+a.keyCode)>=0)G(null,null,!1,!1,!1),D("k"+f+":"+a.keyIdentifier+":"+a.keyCode),a.preventDefault(),a.stopPropagation()},G=function(a,n,f,m,j){q();if(!b.events)window.addEventListener("mousemove",B,!0),window.addEventListener("mousewheel",Q,!0),b.events=!0;if(location.hostname=="mail.google.com"){var e=document.body.children[1],h=function(){q();e.removeEventListener("DOMSubtreeModified",
h,!0)};e.addEventListener("DOMSubtreeModified",h,!0)}b.startPoint=a?{x:a.x,y:a.y}:null;b.targets=n?[n]:[];b.selection=window.getSelection().toString();b.selrange=window.getSelection().rangeCount>0?window.getSelection().getRangeAt(0):null;b.timeout=null;b.line=!f||!a?null:{code:"",points:[{x:a.x,y:a.y}],dirPoints:[{x:a.x,y:a.y}],possibleDirs:o,distance:0};b.rocker=m;b.wheel=j;document.documentElement.offsetHeight<document.documentElement.scrollHeight&&(b.line||b.wheel)&&!u.parentNode&&document.body.appendChild(u)},
B=function(a,n){if(!b.startPoint)b.startPoint={x:a.clientX,y:a.clientY};if(b.rocker||b.wheel)if(Math.abs(a.clientX-b.startPoint.x)>0||Math.abs(a.clientY-b.startPoint.y)>2)b.rocker=null,b.wheel=null;if(b.line){var f={x:a.clientX,y:a.clientY},m=b.line.points[b.line.points.length-1];b.line.points.push(f);b.line.distance+=Math.sqrt(Math.pow(f.x-m.x,2)+Math.pow(f.y-m.y,2));var g=f.x-b.line.dirPoints[b.line.dirPoints.length-1].x,e=f.y-b.line.dirPoints[b.line.dirPoints.length-1].y;if(!j.trailBlock&&l.getContext){var h=
l.getContext("2d");h.strokeStyle="rgba("+j.trailColor.r+","+j.trailColor.g+","+j.trailColor.b+","+j.trailColor.a+")";h.lineWidth=j.trailWidth;h.lineCap="butt";h.beginPath();h.moveTo(m.x,m.y);h.lineTo(f.x,f.y);h.stroke();E();!l.parentNode&&(Math.abs(g)>10||Math.abs(e)>10)&&document.body.appendChild(l)}var m=b.line.code==""?"X":b.line.code.substr(-1,1),h=null,o=!1;Math.abs(g)>2*Math.abs(e)?h=g>0?"R":"L":Math.abs(e)>2*Math.abs(g)?h=e>0?"D":"U":e<0?(o=!0,h=g<0?"7":"9"):(o=!0,h=g<0?"1":"3");if(h==m)b.line.dirPoints[b.line.dirPoints.length-
1]=f;else if((!o||n)&&(Math.abs(g)>15||Math.abs(e)>15)){if(b.line.possibleDirs)b.line.possibleDirs=b.line.possibleDirs[h];b.line.possibleDirs||k.callback?(b.line.code+=h,b.line.dirPoints.length>1&&b.line.dirPoints.push(f),b.line.dirPoints.push(f)):(q(),s=!0)}}},Q=function(a){(a.target.nodeName=="IFRAME"||a.target.nodeName=="FRAME")&&q();B(a);if(b.wheel){var n=a.wheelDelta>0?"U":"D";if(k.callback||o.w[n])x={timeout:setTimeout(function(){x=!1},500)},D("w"+n),j.holdButton==2&&(s=!0),j.holdButton==0&&
window.getSelection().removeAllRanges(),p[j.holdButton]=!0,a.preventDefault(),a.stopPropagation()}},D=function(a){if(a)if(k.callback)k.callback(a),k.callback=null;else{var n=null;if(b.selection.length>0&&b.selrange)n=document.createElement("div"),n.appendChild(b.selrange.cloneContents()),n=n.innerHTML;n={gesture:a,startPoint:b.startPoint,targets:[],links:[],images:[],selection:b.selection,selectionHTML:n};if(b.line&&a[0]!="w"&&a[0]!="r")n.line={distance:b.line.distance,segments:a.length};if(j.selectToLink&&
b.selection){parts=b.selection.split("http");for(var f=1;f<parts.length;f++){var m="http"+parts[f],m=m.split(/[\s"']/)[0];m.match(/\/\/.+\..+/)&&n.links.push({src:m})}}for(f=0;f<b.targets.length;f++){var l=(""+Math.random()).substr(2);b.targets[f].gestureid=l;n.targets.push({gestureid:l});(m=P(b.targets[f]))&&n.links.push({src:m,gestureid:l});b.targets[f].nodeName=="IMG"&&n.images.push({src:b.targets[f].src,gestureid:l})}if(x)n.buttonDown=g;r.postMessage(JSON.stringify(n))}a[0]=="w"?(b.line=null,
b.rocker=null):a[0]=="r"?(b.line=null,b.wheel=null):q()},q=function(){if(b.events)window.removeEventListener("mousemove",B,!0),window.removeEventListener("mousewheel",Q,!0),b.events=!1;l.parentNode&&l.parentNode.removeChild(l);l.getContext&&l.getContext("2d").clearRect(0,0,l.width,l.height);u.parentNode&&u.parentNode.removeChild(u);clearTimeout(b.timeout);b.timeout=null;b.line=null;b.rocker=null;b.wheel=null},P=function(a){for(;a;){if(a.href)return a.href;a=a.parentNode}return null},E=function(){if(!E.timeout)E.timeout=
setTimeout(function(){if(l.getContext){var a=l.getContext("2d");a.strokeStyle="rgba("+j.trailColor.r+","+j.trailColor.g+","+j.trailColor.b+","+j.trailColor.a+")";a.lineWidth=j.trailWidth;a.lineCap="butt";a.lineJoin="round";a.clearRect(0,0,l.width,l.height);if(b.line){a.beginPath();a.moveTo(b.line.points[0].x,b.line.points[0].y);for(var n=1;n<b.line.points.length;n++)a.lineTo(b.line.points[n].x,b.line.points[n].y);a.stroke()}}E.timeout=null},200)};k.drawGesture=function(a,b,f,m){var g="";a[0]=="s"?
(g="s",a=a.substr(1)):a[0]=="l"?(g="l",a=a.substr(1)):a[0]=="i"&&(g="i",a=a.substr(1));if(a[0]=="r")var f=a,m=f[1]=="L"?0:f[1]=="M"?1:2,e=f[2]=="L"?0:f[2]=="M"?1:2,f=$("<div>").css({width:b+"px"}).append($("<div>").text(chrome.i18n.getMessage("gesture_"+f)).css({"font-size":0.8*Math.sqrt(b/100)+"em",color:"#111","text-align":"center","font-weight":"bold"})).append($("<div>").text(chrome.i18n.getMessage("gesture_rocker_descrip",[chrome.i18n.getMessage("options_mousebutton_"+m),chrome.i18n.getMessage("options_mousebutton_"+
e)])).css({"font-size":0.8*Math.sqrt(b/100)+"em",color:"#666","text-align":"center"}));else f=a[0]=="w"?$("<div>").css({width:b+"px"}).append($("<div>").text(chrome.i18n.getMessage("gesture_"+a)).css({"font-size":0.8*Math.sqrt(b/100)+"em",color:"#111","text-align":"center","font-weight":"bold"})).append($("<div>").text(chrome.i18n.getMessage("gesture_"+a+"_descrip")).css({"font-size":0.8*Math.sqrt(b/100)+"em",color:"#666","text-align":"center"})):a[0]=="k"?$("<div>").css({width:b+"px"}).append($("<div>").text((a[1]==
"1"?"Ctrl + ":"")+(a[2]=="1"?"Alt + ":"")+(a[3]=="1"?"Shift + ":"")+(a[4]=="1"?"META + ":"")+R(a)).css({"font-size":0.8*Math.sqrt(b/100)+"em",color:"#666","text-align":"center","font-weight":"bold"})):S(a,b,f,m);$(f).css({"min-height":"2em",overflow:"hidden"});m=null;g=="s"?m="* "+chrome.i18n.getMessage("context_with_selection"):g=="l"?m="* "+chrome.i18n.getMessage("context_on_link"):g=="i"?m="* "+chrome.i18n.getMessage("context_on_image"):bg&&(bg.gestures["s"+a]?m="* "+chrome.i18n.getMessage("context_not_selection"):
bg.gestures["l"+a]&&bg.gestures["i"+a]?m="* "+chrome.i18n.getMessage("context_not_links_images"):bg.gestures["l"+a]?m="* "+chrome.i18n.getMessage("context_not_link"):bg.gestures["i"+a]&&(m="* "+chrome.i18n.getMessage("context_not_image")));return m?$("<div>").css({width:b+"px",overflow:"hidden"}).append($("<div>").css({"font-size":0.8*Math.sqrt(b/100)+"em",color:"#888","text-align":"right","margin-right":".3em"}).text(m)).append(f):f};var S=function(a,b,f,g){var l=document.createElement("canvas");
l.width=b;l.height=f;ctx=l.getContext("2d");ctx.strokeStyle="rgba("+j.trailColor.r+","+j.trailColor.g+","+j.trailColor.b+","+j.trailColor.a+")";ctx.lineWidth=g?g:3;ctx.lineCap="butt";var e=10,h=2,k=3,c={x:0,y:0},d={x:0,y:0},o={x:0,y:0},p={x:0,y:0},r=function(a){c=d;ctx.lineTo(c.x,c.y);a=="U"?d={x:c.x,y:c.y-e*0.75}:a=="D"?d={x:c.x,y:c.y+e*0.75}:a=="L"?d={x:c.x-e*0.75,y:c.y}:a=="R"?d={x:c.x+e*0.75,y:c.y}:a=="1"?d={x:c.x-e*0.5,y:c.y+e*0.5}:a=="3"?d={x:c.x+e*0.5,y:c.y+e*0.5}:a=="7"?d={x:c.x-e*0.5,y:c.y-
e*0.5}:a=="9"&&(d={x:c.x+e*0.5,y:c.y-e*0.5});ctx.lineTo(d.x,d.y);s()},g=function(a){c=d;ctx.lineTo(c.x,c.y);a=="UD"?(d={x:c.x,y:c.y-e},s(),ctx.lineTo(c.x,c.y-e),ctx.arc(c.x+h,c.y-e,h,Math.PI,0,!1),ctx.lineTo(c.x+h*2,c.y)):a=="UL"?ctx.arc(c.x-e,c.y,e,0,-Math.PI/2,!0):a=="UR"?ctx.arc(c.x+e,c.y,e,Math.PI,-Math.PI/2,!1):a=="DU"?(d={x:c.x,y:c.y+e},s(),ctx.lineTo(c.x,c.y+e),ctx.arc(c.x+h,c.y+e,h,Math.PI,0,!0),ctx.lineTo(c.x+h*2,c.y)):a=="DL"?ctx.arc(c.x-e,c.y,e,0,Math.PI/2,!1):a=="DR"?ctx.arc(c.x+e,c.y,
e,Math.PI,Math.PI/2,!0):a=="LU"?ctx.arc(c.x,c.y-e,e,Math.PI/2,Math.PI,!1):a=="LD"?ctx.arc(c.x,c.y+e,e,-Math.PI/2,Math.PI,!0):a=="LR"?(d={x:c.x-e,y:c.y},s(),ctx.lineTo(c.x-e,c.y),ctx.arc(c.x-e,c.y+h,h,-Math.PI/2,Math.PI/2,!0),ctx.lineTo(c.x,c.y+h*2)):a=="RU"?ctx.arc(c.x,c.y-e,e,Math.PI/2,0,!0):a=="RD"?ctx.arc(c.x,c.y+e,e,-Math.PI/2,0,!1):a=="RL"?(d={x:c.x+e,y:c.y},s(),ctx.lineTo(c.x+e,c.y),ctx.arc(c.x+e,c.y+h,h,-Math.PI/2,Math.PI/2,!1),ctx.lineTo(c.x,c.y+h*2)):(r(a[0]),r(a[1]));a=="UD"?d={x:c.x+h*
2,y:c.y+k}:a=="UL"?d={x:c.x-e,y:c.y-e}:a=="UR"?d={x:c.x+e+k,y:c.y-e}:a=="DU"?d={x:c.x+h*2,y:c.y}:a=="DL"?d={x:c.x-e,y:c.y+e}:a=="DR"?d={x:c.x+e+k,y:c.y+e}:a=="LU"?d={x:c.x-e,y:c.y-e}:a=="LD"?d={x:c.x-e,y:c.y+e+k}:a=="LR"?d={x:c.x+k,y:c.y+h*2}:a=="RU"?d={x:c.x+e,y:c.y-e}:a=="RD"?d={x:c.x+e,y:c.y+e+k}:a=="RL"&&(d={x:c.x,y:c.y+h*2});s()},s=function(){if(d.x>o.x)o.x=d.x;if(d.y>o.y)o.y=d.y;if(d.x<p.x)p.x=d.x;if(d.y<p.y)p.y=d.y};ctx.beginPath();r(a[0]);for(i=0;i<a.length-1;i++)g(a[i]+a[i+1]);r(a[a.length-
1]);ctx.stroke();var t={x:(o.x+p.x)/2,y:(o.y+p.y)/2},q=(o.x-p.x+e)/b,u=(o.y-p.y+e)/f,q=u>q?u:q;e/=q;k/=q;h/=q;h>6&&(h=6);d={x:0,y:0};ctx.clearRect(0,0,l.width,l.height);ctx.save();ctx.translate(b/2-t.x/q,f/2-t.y/q);ctx.beginPath();r(a[0]);for(i=0;i<a.length-1;i++)g(a[i]+a[i+1]);r(a[a.length-1]);ctx.stroke();ctx.fillStyle="rgba("+j.trailColor.r+","+j.trailColor.g+","+j.trailColor.b+","+j.trailColor.a+")";ctx.beginPath();a[a.length-1]=="U"?(ctx.moveTo(d.x-5,d.y+2),ctx.lineTo(d.x+5,d.y+2),ctx.lineTo(d.x,
d.y-3)):a[a.length-1]=="D"?(ctx.moveTo(d.x-5,d.y-2),ctx.lineTo(d.x+5,d.y-2),ctx.lineTo(d.x,d.y+3)):a[a.length-1]=="L"?(ctx.moveTo(d.x+2,d.y-5),ctx.lineTo(d.x+2,d.y+5),ctx.lineTo(d.x-3,d.y)):a[a.length-1]=="R"?(ctx.moveTo(d.x-2,d.y-5),ctx.lineTo(d.x-2,d.y+5),ctx.lineTo(d.x+3,d.y)):a[a.length-1]=="1"?(ctx.moveTo(d.x-2,d.y-6),ctx.lineTo(d.x+6,d.y+2),ctx.lineTo(d.x-2,d.y+2)):a[a.length-1]=="3"?(ctx.moveTo(d.x+2,d.y-6),ctx.lineTo(d.x-6,d.y+2),ctx.lineTo(d.x+2,d.y+2)):a[a.length-1]=="7"?(ctx.moveTo(d.x-
2,d.y+6),ctx.lineTo(d.x+6,d.y-2),ctx.lineTo(d.x-2,d.y-2)):a[a.length-1]=="9"&&(ctx.moveTo(d.x+2,d.y+6),ctx.lineTo(d.x-6,d.y-2),ctx.lineTo(d.x+2,d.y-2));ctx.closePath();ctx.fill();ctx.restore();return l},T={8:"Backspace",9:"Tab",13:"Enter",19:"Pause",20:"Caps Lock",27:"Esc",32:"Space",33:"Page Up",34:"Page Down",35:"End",36:"Home",37:"Left",38:"Up",39:"Right",40:"Down",45:"Insert",46:"Delete",96:"NP 0",97:"NP 1",98:"NP 2",99:"NP 3",100:"NP 4",101:"NP 5",102:"NP 6",103:"NP 7",104:"NP 8",105:"NP 9",
106:"NP *",107:"NP +",109:"NP -",110:"NP .",111:"NP /",144:"Num Lock",145:"Scroll Lock",186:";",187:"=",188:",",189:"-",190:".",191:"/",192:"~",219:"[",220:"\\",221:"]",222:"'"},R=function(a){var a=a.split(":"),b=a[1],a=a[2];if(!b||b=="")return"empty";if(b.substr(0,2)!="U+")return b;if(a=T[a])return a;return eval('"\\u'+b.substr(2)+'"')};k.disable=function(){z&&(z=!1,window.removeEventListener("mousedown",J,!0),window.removeEventListener("mouseup",K,!0),window.removeEventListener("click",L,!0),window.removeEventListener("contextmenu",
M,!0),window.removeEventListener("selectstart",N,!0),window.removeEventListener("resize",F,!0),window.removeEventListener("keydown",O,!0),r.onMessage.removeListener(I),r.onDisconnect.removeListener(k.disable))};k.enabled=function(){return z};k.extVersion=function(){return v};k.setSettings=function(a){j=a};window.addEventListener("focus",function(a){if(a.target.nodeName)A=a.target},!0);window.addEventListener("blur",function(a){a.target.nodeName&&(A=null)},!0);k.connect();l=document.createElement("canvas");
if(l.style)l.style.position="fixed",l.style.top=0,l.style.left=0,l.style.zIndex=10001;F();u=document.createElement("div");if(u.style)u.style.clear="both"};if(window.SGinjectscript&&window.SGinjectscript.constructor==HTMLScriptElement){var match=window.SGinjectscript.src.match(/([^a-p]|^)([a-p]{32})([^a-p]|$)/);if(match)window.SGextId=match[2];for(var scripts=document.querySelectorAll("script[src^=chrome-extension\\:\\/\\/]"),i=0;i<scripts.length;i++)scripts[i].parentNode.removeChild(scripts[i])}
window.SG?window.SG.enabled()||window.SG.connect():window.SG=new SmoothGestures;